buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.74.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'
rootProject.name = 'gradle-idea-language-injector-root'

include 'gradle-idea-language-injector'
include 'test-libraries:simple-lib'
include 'test-libraries:complex-lib'
include 'test-libraries:noannotations-lib'
