com.fasterxml.jackson.core:jackson-annotations = 2.21
com.netflix.nebula:nebula-test = 12.1.0
junit:junit = 4.13.2
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:* = 6.1.2
org.junit.vintage:* = 6.1.2
org.junit.platform:* = 6.1.2
com.fasterxml.jackson.*:* = 2.21.4
org.ow2.asm:asm = 9.10.1
org.immutables:value = 2.12.2
