com.fasterxml.jackson.core:jackson-annotations = 2.20
com.netflix.nebula:nebula-test = 10.6.2
junit:junit = 4.13.2
org.assertj:assertj-core = 3.27.6
org.junit.jupiter:* = 6.0.2
org.junit.vintage:* = 6.0.2
org.junit.platform:* = 6.0.2
com.fasterxml.jackson.*:* = 2.20.1
org.ow2.asm:asm = 9.9.1
org.immutables:value = 2.12.0
