com.fasterxml.jackson.core:jackson-annotations = 2.21
com.netflix.nebula:nebula-test = 10.6.2
junit:junit = 4.13.2
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:* = 6.0.3
org.junit.vintage:* = 6.1.0
org.junit.platform:* = 6.1.0
com.fasterxml.jackson.*:* = 2.21.1
org.ow2.asm:asm = 9.10
org.immutables:value = 2.12.2
