apply plugin: 'java'
apply plugin: 'maven-publish'

group = 'com.example'
version = '1.0.0'

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.0.1'
}

// Disable baseline checks for test library code
tasks.withType(JavaCompile) {
    options.errorprone.enabled = false
}
tasks.withType(Checkstyle) {
    enabled = false
}
