apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'java-gradle-plugin'
apply plugin: 'groovy'
apply plugin: 'com.palantir.external-publish-jar'


dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-guava'
    implementation 'org.ow2.asm:asm'

    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value::annotations'

    testImplementation gradleTestKit()
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
}

tasks.withType(Test) {
    useJUnitPlatform()
    dependsOn ':test-libraries:simple-lib:publishToMavenLocal'
    dependsOn ':test-libraries:complex-lib:publishToMavenLocal'
    dependsOn ':test-libraries:noannotations-lib:publishToMavenLocal'
}

gradlePlugin {
    website = 'https://github.com/palantir/gradle-idea-language-injector'
    vcsUrl = 'https://github.com/palantir/gradle-idea-language-injector'

    plugins {
        ideaLanguageInjector {
            id = 'com.palantir.idea-language-injector'
            implementationClass = 'com.palantir.gradle.idealanguageinjector.IdeaLanguageInjectorRootPlugin'
            displayName = 'Settings plugin to manage IDEA configuration files'
            description = displayName
        }
    }
}

gradleTestUtils {
    gradleVersions = ['8.14.3']
}
